{"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serverError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"statusCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The server returned an error response"}],"variants":[{"paths":["\/documentation\/network\/networkerror\/servererror(statuscode:data:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","modules":[{"name":"Network"}],"symbolKind":"case","externalID":"s:7Network0A5ErrorO06serverB0yACSi_10Foundation4DataVtcACmF","title":"NetworkError.serverError(statusCode:data:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":")"}],"roleHeading":"Case"},"kind":"symbol","identifier":{"url":"doc:\/\/Network\/documentation\/Network\/NetworkError\/serverError(statusCode:data:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/Network\/documentation\/Network","doc:\/\/Network\/documentation\/Network\/NetworkError"]]},"sections":[],"references":{"doc://Network/documentation/Network/NetworkError/serverError(statusCode:data:)":{"url":"\/documentation\/network\/networkerror\/servererror(statuscode:data:)","role":"symbol","identifier":"doc:\/\/Network\/documentation\/Network\/NetworkError\/serverError(statusCode:data:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":")"}],"title":"NetworkError.serverError(statusCode:data:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The server returned an error response"}]},"doc://Network/documentation/Network":{"identifier":"doc:\/\/Network\/documentation\/Network","url":"\/documentation\/network","abstract":[],"role":"collection","type":"topic","title":"Network","kind":"symbol"},"doc://Network/documentation/Network/NetworkError":{"identifier":"doc:\/\/Network\/documentation\/Network\/NetworkError","type":"topic","title":"NetworkError","abstract":[{"text":"Errors that can occur during network operations.","type":"text"}],"url":"\/documentation\/network\/networkerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkError","kind":"identifier"}],"navigatorTitle":[{"text":"NetworkError","kind":"identifier"}],"kind":"symbol","role":"symbol"}}}